version: '3.8'
# it overrides, so make sure to change the variables declared in .yml, which are unwanted in prod.yml
# https://docs.docker.com/compose/extends/#different-environments
services:
  api:
    build:
        context: ./backend
        dockerfile: Dockerfile.prod
  frontend:
    build:
        context: ./frontend
        dockerfile: Dockerfile.prod